### ISSUE TITLE
Display ECA - not enough Decimals

### ISSUE THREAD

**Issue by ruannelloyd** [Electra-project/electra-desktop#82] opened 2018-04-17 12:05 UTC
![screenshot 2018-04-17 14 02 31](https://user-images.githubusercontent.com/35781921/38868714-4fbf4e06-4248-11e8-87fe-6b38605dbf27.png)

**Comment by ivangabriele** [comment] 2018-06-06 07:19
Closed as duplicate of #95.

**Closed by ivangabriele** 2018-06-06 07:19 UTC
Labels: bug, duplicate, information required
