### ISSUE TITLE
Can't send from legacy to checking W10

### ISSUE THREAD

**Issue by Jenova7** [Electra-project/electra-desktop#110] opened 2018-04-21 13:57 UTC
We delete Electra desktop folder, restart wallet, same issue
after, uninstall properly the wallet, fresh install, wait for full synch. 
Try to send all (-fees), still the same.

**Comment by ivangabriele** [comment] 2018-05-31 09:37
You were trying to send  the full amount available in your Legacy Account ?

**Comment by Jenova7** [comment] 2018-05-31 16:38
yes, it's a duplicate, answered on the #121

**Comment by ivangabriele** [comment] 2018-05-31 22:18
Close as duplicate of #121.

**Closed by ivangabriele** 2018-05-31 22:18 UTC
Labels: duplicate
