### ISSUE TITLE
Blank (white) wallet on Ubuntu 18.04

### ISSUE THREAD

**Issue by novize001** [Electra-project/electra-desktop#119] opened 2018-05-16 07:23 UTC
The wallet shows a window which is completely white. I can't move the window, however I can open / close it to / from the systray. I'm also able to resize the white wallet window.  Running the command "electra-desktop" from a terminal gives the following output:

> electra-desktop
>(node:2514) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'autoUpdate' of undefined
>(node:2514) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
>The wallet daemon process exited with the code: 0.

I used the prebuild Debian packages. The old Qt wallet is closed.

**Comment by ivangabriele** [comment] 2018-05-31 08:33
I have the same bug under Lubuntu and I really have no idea right now why it does that. It seems to happen when the wallet stays open for a long time, is it the behavior you also have ?

**Comment by ivangabriele** [comment] 2018-05-31 08:41
Also, if you exit and start the wallet again, can you confirm that it does go back to normal ?

**Comment by ivangabriele** [comment] 2018-06-15 06:45
It seems fixed in the v1.1.0. I'm letting a Lubuntu VM with an open wallet to confirm that the switch to Electron v2 fixed it.

**Comment by ivangabriele** [comment] 2018-06-15 22:17
I close this one since I confirm I don't reproduce the error anymore one the v1.1.0:

- Linux (.deb): https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop_1.1.0_amd64.deb
- Linux (.rpm): https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop-1.1.0.x86_64.rpm
- MacOS: https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop-1.1.0.dmg
- Windows: https://github.com/Electra-project/storage/releases/download/v0.0.0/electra-desktop-setup-1.1.0.exe

**Closed by ivangabriele** 2018-06-15 22:17 UTC
Labels: bug, under investigation
